rest:
  name: jacana-rest-api 
  replicaCount: 1
  image: localhost:5000/jacana-rest-api:latest
  containerPort: 8080
  port: 8080

mysql:
  name: mysql
  image: mysql:8.4
  port: 3306

logging:
  visualization:
    enabled: true

elasticsearch:
  name: elasticsearch
  image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
  containerPort: 9200 

kibana:
  name: kibana
  image: docker.elastic.co/kibana/kibana:7.9.3
  containerPort: 5601 
