{{ if .Values.logging.visualization.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
  ports:
  - port: {{ .Values.elasticsearch.containerPort }}
    targetPort: es-http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.name }}
        version: v1
    spec:
      containers:
      - name: {{ .Values.elasticsearch.name }}
        image: {{ .Values.elasticsearch.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.elasticsearch.containerPort }}
          name: es-http
        env:
        - name: discovery.type
          value: single-node
{{ end }}
