apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  #  <match **>
  #    @type stdout
  #  </match>
  fluent.conf: |
    <source>
      @type tail
      path /var/log/pods/*{{ .Release.Namespace }}*/*{{ .Values.rest.name }}*/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <match **>
      @type copy
      <store>
        @type stdout
      </store>

      {{ if .Values.logging.visualization.enabled }}
      <store>
        @type elasticsearch
        host elasticsearch.{{ .Release.Namespace }}.svc.cluster.local
        port {{ .Values.elasticsearch.containerPort }}
        logstash_format true
        <buffer>
          flush_interval 5s
        </buffer>
      </store>
      {{ end }}

    </match>
