{{ if .Values.logging.visualization.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.kibana.name }}
  ports:
  - name: tcp
    port: {{ .Values.kibana.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.kibana.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kibana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.name }}
    spec:
      containers:
      - name: {{ .Values.kibana.name }}
        image: {{ .Values.kibana.image }}
        ports:
        - containerPort: {{ .Values.kibana.containerPort }}
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.elasticsearch.containerPort }}"
{{ end }}
