kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rest.name }}
  labels:
    app: {{ .Values.rest.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.rest.name }}
  ports:
    - name: tcp
      port: {{ .Values.rest.port }}
      protocol: TCP
      targetPort: {{ .Values.rest.containerPort }}
---
{{ if .Values.logging.visualization.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
  ports:
  - port: {{ .Values.elasticsearch.containerPort }}
    targetPort: es-http
{{ end }}
---
{{ if .Values.logging.visualization.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.kibana.name }}
  ports:
  - name: tcp
    port: {{ .Values.kibana.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.kibana.containerPort }}
{{ end }}
